#include <wchar.h>
#include <wctype.h>
#include <CONIO.H>
#include <CTYPE.H>
#include <dir.h>
#include <DIRECT.H>
//#include <dirent.h>
#include <DOS.H>
#include <ERRNO.H>
#include <excpt.h>
#include <FCNTL.H>
#include <fenv.h>
#include <FLOAT.H>
#include <getopt.h>
//#include <gmon.h>
//#include <inttypes.h>
#include <IO.H>
//#include <IOSTREAM.H>
#include <LIMITS.H>
#include <LOCALE.H>
#include <MALLOC.H>
#include <MATH.H>
#include <mbctype.h>
#include <mbstring.h>
#include <mem.h>
#include <MEMORY.H>
#include <PROCESS.H>
//#include <profil.h>
#include <profile.h>
#include <SEARCH.H>
#include <SETJMP.H>
#include <SHARE.H>
#include <SIGNAL.H>
#include <STDARG.H>
#include <STDDEF.H>
//#include <stdint.h>
#include <STDIO.H>
#include <STDLIB.H>
#include <STRING.H>
#include <strings.h>
#include <TCHAR.H>
#include <TIME.H>
#include <unistd.h>
//#include <utime.h>
#include <values.h>
//#include <VARARGS.H>
